### ISSUE TITLE
hc10 - 도시락통 & kakao i

### ISSUE THREAD

**Issue by KimIronSword** [KimIronSword/wtf#4]
---header
![logo](https://user-images.githubusercontent.com/109255531/179461320-80c61e03-3dcd-4b47-8978-591e3c231ae8.png)

---main
![main_visual_1](https://user-images.githubusercontent.com/109255531/179461360-d545570e-4960-499d-a95a-1536edae5d1c.jpg)
![main_visual_2](https://user-images.githubusercontent.com/109255531/179461367-e151a4c5-2bd8-4f9e-b074-f30ddd69f1db.jpg)
![main_visual_3](https://user-images.githubusercontent.com/109255531/179461370-141420b4-ba36-40a3-9932-d71a0b93e9b0.jpg)
![main_visual_4](https://user-images.githubusercontent.com/109255531/179461371-7f480487-2b67-4d82-b762-0210ba66c605.jpg)

---service
![main_service_img1](https://user-images.githubusercontent.com/109255531/179461426-c771c584-e827-4d39-b14b-307177a3f027.jpg)
![main_service_img2](https://user-images.githubusercontent.com/109255531/179461433-2e5914bd-e16c-446f-b18c-bae34effce30.jpg)
![main_service_img3](https://user-images.githubusercontent.com/109255531/179461437-401fc6b6-1f28-43e9-80ed-8204526ed556.jpg)

---footer?menu?
![main_banner_figure2](https://user-images.githubusercontent.com/109255531/179461507-738a506c-682f-4f80-b1f9-be19742905be.png)
![main_banner_figure3](https://user-images.githubusercontent.com/109255531/179461509-f4dcfc35-f433-412e-8be4-552e418a6fca.png)
![main_banner_figure1](https://user-images.githubusercontent.com/109255531/179461504-49adab83-4da9-4835-9cd2-cfd8cf2f2a3a.png)

---to top
![arrow-137-512](https://user-images.githubusercontent.com/109255531/179461621-1520b4b2-d819-4176-afb7-e43b21e63a72.png)

---script?
![logo_white](https://user-images.githubusercontent.com/109255531/179461572-c321094e-aca3-49d2-b648-87313f561f33.png)
![scroll_guide2](https://user-images.githubusercontent.com/109255531/179461575-0f8061e0-b7f8-4b33-8784-279ae057b070.png)

**Comment by KimIronSword** [comment]
hamburger???
![Hamburger_icon_white](https://user-images.githubusercontent.com/109255531/179461889-a16ffb67-38f3-4093-8c9c-fb07d369340a.svg)

햄버거 마크랑 to top은 구글링 해서 찾은 이미지입니다.

**Comment by KimIronSword** [comment]
hamburger!!!!
![Hamburger_icon](https://user-images.githubusercontent.com/109255531/179462451-34043088-c2c0-47eb-bddd-a313cdabbdc6.svg)

검은거 써야 되는구나 ㅎㅎ;;

**Comment by KimIronSword** [comment]
![main_content_fullscreen_slider_controller_next](https://user-images.githubusercontent.com/109255531/179469546-88b6390c-2c2a-47bc-956c-9ed9d6e58d7d.png)

날 미치게 하는군!

**Comment by KimIronSword** [comment]
2위
---main
![다운로드](https://user-images.githubusercontent.com/109255531/180143530-f2a04236-27ad-4f91-92ea-1cbeee872cb3.jpg)

---product
![다운로드 (1)](https://user-images.githubusercontent.com/109255531/180143663-384e4a00-f8d9-4b91-945a-7df82d640a74.jpg)
![다운로드 (2)](https://user-images.githubusercontent.com/109255531/180143670-812e3d1c-7d6a-472c-a589-5f06ba73363a.jpg)

---make-value
![다운로드 (5)](https://user-images.githubusercontent.com/109255531/180143772-874ae429-e739-4ce0-9c4b-f9bac5763dbc.jpg)
![다운로드 (4)](https://user-images.githubusercontent.com/109255531/180143778-57bfe8c9-af89-44ee-8a22-e1fe571d9d3f.jpg)
![다운로드 (3)](https://user-images.githubusercontent.com/109255531/180143779-08368814-9588-410b-8fcf-ae78990a72ce.jpg)

**Comment by KimIronSword** [comment]
![image_readtop_2017_632107_15058905053036506](https://user-images.githubusercontent.com/109255531/180147959-9f2f11ad-4ec4-497b-bf34-7bbbf56ca478.jpg)
![park you](https://user-images.githubusercontent.com/109255531/180152886-a726fc60-b204-4715-be1d-59cdf0e77d0a.png)

**Comment by KimIronSword** [comment]
![arrow+top+arrow+up+arrow+upward+top+up+upward+icon-1320185743440304413](https://user-images.githubusercontent.com/109255531/180148476-46040499-5f45-49ba-a130-f789fb653af9.png)
haaaaaaa......................................

**Comment by lunaxislu** [comment]
THANKS for your mercy

**Comment by KimIronSword** [comment]
![다운로드](https://user-images.githubusercontent.com/109255531/180715134-c381f300-0203-40ff-8112-9be5de5b7517.jpg)
하지 말까 했는데 걍 함
개같은거
